notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'


urlpatterns = [
    ################## Notes urls##############################

    path('', views.home_page,name='home-page'),
    path('notes-page/', views.notes_page, name='notes_page'),
    path('add-note/', views.add_note, name='add-note'),
    path('delete-note/<note_id>',views.delete_note,name='delete-note'),
    path('update-note/<note_id>',views.update_note,name='update-note'),
    path('search-page/', views.search_page, name = 'search-page'),
    path('pin-note/<note_id>', views.pin_note,name='pin-note'),
    path('favorite-note/<note_id>', views.favorite_note,name='favorite-note'),
    path('favorite-notes-page', views.favorite_notes_page, name="favorite-notes-page"),

    ############ Cateogries urls#######################

    path('category-page/<category_id>', views.category_page,name='category-page'),

    path('add-note-category/<category_id>', views.add_note_category, name='add-note-category'),

    path('delete-note-category/<note_id>/<category_id>',views.delete_note_category,name='delete-note-category'),

    path('update-note-category/<note_id>/<category_id>',views.update_note_category,name='update-note-category'),

    path('add-category', views.add_category, name='add-category'),

    path('delete-category/<category_id>', views.delete_category,name='delete-category'),

    path('update-category/<category_id>', views.update_category,name='update-category'),

    path('pin-category-note/<note_id>/<category_id>', views.pin_category_note,name='pin-category-note'),

    path('favorite-category-note/<note_id>/<category_id>', views.favorite_category_note,name='favorite-category-note'),

    #### Favorite notes page########
    path('pin-note_on_page/<note_id>', views.pin_note_on_page,name='pin-note-on-page'),
    path('favorite-note-on-page/<note_id>', views.favorite_note_on_page,name='favorite-note-on-page'),

]

notesapp/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('',include('notes.urls')),
    path('users/',include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'


urlpatterns = [
    path('register/', views.register_user, name = 'register-user'),
    path('login/', views.login_user, name = 'login-user'),
    path('logout/', views.logout_user, name = 'logout-user'),
    
]

notes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50)
    author = models.ForeignKey(User,on_delete=models.CASCADE,default=None)

    def __str__(self):
        return self.name
    


class Note(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE,blank=True,null=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE,default=None)
    rank = models.IntegerField(default=0)
    is_pinned = models.BooleanField(default=False)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.title
    

notes/forms.py
from django.forms import ModelForm
from . import models
from django import forms


class NoteForm(ModelForm):
    class Meta:
        model = models.Note
        fields = ['title','content', 'category']
        

        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter a title'
            }),
            'content': forms.Textarea(attrs={
                'class': 'form-control',
                'rows' : 6,
                'placeholder': 'Write your note...'
            }),
            'category':forms.Select(attrs={
                'class' : 'form-select'
            }),
        }

    def __init__(self,*args,**kwargs):
        user = kwargs.pop('user',None)
        super().__init__(*args,**kwargs)
        if user:
            self.fields['category'].queryset = models.Category.objects.filter(author = user)


class CategoryForm(ModelForm):
    class Meta:
        model = models.Category
        fields = ['name']

notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import models
from .forms import NoteForm, CategoryForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .helpers import handle_pin_notes

def home_page(request):
    return render(request, 'notes/home_page.html')


# ############################ Notes #########################

@login_required(login_url='users:login-user')
def notes_page(request):
    notes = models.Note.objects.filter(author=request.user).order_by("-is_pinned", "-rank")

    total_notes = len(notes)

    pinned_notes = notes.filter(is_pinned=True).count()

    favorite_notes = notes.filter(is_favorite=True).count()

    categories = models.Category.objects.filter(author=request.user)

    total_categories =len(categories)

    return render(request, 'notes/notes_page.html', {'notes': notes, "categories": categories, 'total_notes':total_notes,'pinned_notes':pinned_notes, "favorite_notes":favorite_notes,"total_categories": total_categories})


@login_required(login_url='users:login-user')
def add_note(request):
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.author = request.user
            new_note.save()
            messages.success(request, "Note added successfully!")
            return redirect('notes:notes_page')
    else:
        form = NoteForm(user = request.user)
    return render(request, 'notes/add_note.html', {'form': form})


@login_required(login_url='users:login-user')
def delete_note(request, note_id):
    note = get_object_or_404(models.Note, pk=note_id, author=request.user)
    if request.method == 'POST':
        note.delete()
        messages.warning(request, "Note deleted successfully!")
    return redirect('notes:notes_page')


@login_required(login_url='users:login-user')
def update_note(request, note_id):
    note = get_object_or_404(models.Note, pk=note_id, author=request.user)
    if request.method == 'POST':
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            form.save()
            messages.success(request, "Note updated successfully!")
            return redirect("notes:notes_page")
    else:
        form = NoteForm(instance=note, user = request.user)
    return render(request, 'notes/update_note.html', {'form': form})


@login_required(login_url='users:login-user')
def search_page(request):
    if request.method == 'POST':
        searched = request.POST.get('searched', '').strip()
        notes = models.Note.objects.filter(title__icontains=searched, author=request.user)
        return render(request, 'notes/search_page.html', {'searched': searched, 'notes': notes})
    else:
        return render(request, 'notes/search_page.html', {'searched': '', 'notes': []})

@login_required(login_url="users:login-user")
def pin_note(request,note_id):
    note = get_object_or_404(models.Note,pk=note_id,author=request.user)
    if request.method=="POST":
       return handle_pin_notes(request,'pin',note)

@login_required
def favorite_note(request,note_id):
    note = get_object_or_404(models.Note, pk=note_id, author = request.user)
    if request.method =='POST':
        return handle_pin_notes(request,'favorite',note)


@login_required(login_url='users:login-user')
def favorite_notes_page(request):
    notes = models.Note.objects.filter(author=request.user,is_favorite=True).order_by("-is_pinned", "-rank")
    categories = models.Category.objects.filter(author=request.user)
    return render(request, 'notes/favorite_notes.html', {'notes': notes, "categories": categories})

# ############################ Categories #########################

@login_required(login_url='users:login-user')
def category_page(request, category_id):
    category = get_object_or_404(models.Category, pk=category_id, author=request.user)
    notes = category.note_set.filter(author=request.user).order_by("-is_pinned" , "-rank")
    categories = models.Category.objects.filter(author=request.user)
    return render(request, 'categories/category_page.html', {
        'notes': notes,
        'category': category,
        'categories': categories
    })


@login_required(login_url='users:login-user')
def add_note_category(request, category_id):
    category = get_object_or_404(models.Category, pk=category_id, author=request.user)
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.category = category
            new_note.author = request.user
            new_note.save()
            messages.success(request, "Note added to category successfully!")
            return redirect('notes:category-page', category_id=category_id)
    else:
        form = NoteForm()
    return render(request, 'categories/add_note_category.html', {'form': form, 'category': category})


@login_required(login_url='users:login-user')
def delete_note_category(request, note_id, category_id):
    note = get_object_or_404(models.Note, pk=note_id, author=request.user, category_id=category_id)
    if request.method == 'POST':
        note.delete()
        messages.warning(request, "Note deleted from category successfully!")
    return redirect('notes:category-page', category_id=category_id)


@login_required(login_url='users:login-user')
def update_note_category(request, note_id, category_id):
    note = get_object_or_404(models.Note, pk=note_id, author=request.user, category_id=category_id)
    category = get_object_or_404(models.Category, pk=category_id, author=request.user)

    if request.method == 'POST':
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            updated_note = form.save(commit=False)
            updated_note.category = category
            updated_note.save()
            messages.success(request, "Note updated successfully!")
            return redirect('notes:category-page', category_id=category_id)
    else:
        form = NoteForm(instance=note)

    return render(request, 'categories/update_note_category.html', {'form': form})

@login_required(login_url="users:login-user")
def pin_category_note(request,note_id,category_id):
    note = get_object_or_404(models.Note, pk=note_id, author = request.user, category_id = category_id)
    
    if request.method=="POST":
        return handle_pin_notes(request,'pin',note,'notes:category-page', category_id=category_id)


@login_required
def favorite_category_note(request,note_id,category_id):
    note = get_object_or_404(models.Note, pk=note_id, author = request.user,category_id=category_id)
    if request.method =='POST':
        return handle_pin_notes(request,'favorite',note,"notes:category-page",category_id=category_id)

################################ Cateogries data #################
@login_required(login_url='users:login-user')
def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            new_category = form.save(commit=False)
            new_category.author = request.user
            new_category.save()
            messages.success(request, "Category added successfully!")
            return redirect("notes:notes_page")
    else:
        form = CategoryForm()
    return render(request, 'categories/add_category.html', {'form': form})


@login_required(login_url='users:login-user')
def delete_category(request, category_id):
    category = get_object_or_404(models.Category, pk=category_id, author=request.user)
    if request.method == 'POST':
        category.delete()
        messages.success(request, "Category deleted successfully!")
    return redirect("notes:notes_page")


@login_required(login_url='users:login-user')
def update_category(request, category_id):
    category = get_object_or_404(models.Category, pk=category_id, author=request.user)
    if request.method == "POST":
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, "Category updated successfully!")
            return redirect('notes:notes_page')
    else:
        form = CategoryForm(instance=category)
    return render(request, 'categories/update_category.html', {'form': form})

################## Favorite page #####

@login_required(login_url="users:login-user")
def pin_note_on_page(request,note_id):
    note = get_object_or_404(models.Note,pk=note_id,author=request.user)
    if request.method=="POST":
       return handle_pin_notes(request,'pin',note,"notes:favorite-notes-page")


@login_required
def favorite_note_on_page(request,note_id):
    note = get_object_or_404(models.Note, pk=note_id, author = request.user)
    if request.method =='POST':
        return handle_pin_notes(request,'favorite',note, "notes:favorite-notes-page")

notes/templates/notes/add_note.html
{% extends "layout.html" %}

{% block title %}
    Add Note
{% endblock title %}

{% block content %}
<div class="form-page">
    <div class="form-card">
        <h1><span class="icon"><i class="bi bi-plus-circle-dotted"></i></span>Add a New Note</h1>
        <form id = 'noteForm' action="{% url 'notes:add-note' %}" method="post">
            {% csrf_token %}
            
            <label for="title">Title</label>
            {{ form.title }}

            <label for="content">Content</label>
            {{ form.content }}
            <label for="category">Category</label>
            {{ form.category }}

            <button type="submit">Save Note</button>
        </form>
    </div>
</div>

{% endblock content %}

notes/templates/notes/favorite_notes.html
{% extends "layout.html" %}

{% block title %}
    Favorite Notes Page
{% endblock title %}

{% block content %}

<div class="notes-container">
    <div class="notes-header">
        <h1><i style = "color:gold;font-size:2.3rem;" class="bi bi-star-fill"></i> Your Favorite Notes</h1>
    </div>

    <div class="notes-list">

        <!-- Toasts container -->
        <div class="toast-container position-fixed bottom-0 end-0 p-3" style="z-index: 1100">
            {% if messages %}
                {% for message in messages %}
                <div class="toast align-items-center text-bg-{{ message.tags }} border-0 mb-2"
                    role="alert" aria-live="assertive" aria-atomic="true"
                    data-bs-delay="4000" data-bs-autohide="true">
                    <div class="d-flex">
                        <div class="toast-body">
                            {{ message }}
                        </div>
                        <button type="button" class="btn-close btn-close-white me-2 m-auto"
                                data-bs-dismiss="toast" aria-label="Close"></button>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
        </div>

        {% for note in notes %}
            <div class="note-card">
                <div class="note-header">
                    <h2>{{ note.title }}</h2>
                    <span class="note-date">{{ note.date|date:"M d, Y H:i" }}</span>
                </div>
                <p class="note-content">{{ note.content }}</p>

                <div class="note-actions">

                    <!-- Delete button triggers modal -->
                    <button type="button" class="btn btn-danger" 
                            data-bs-toggle="modal" 
                            data-bs-target="#deleteModal" 
                            data-note-id="{{ note.id }}"
                            data-note-title = "{{note.title}}"
                            >
                        <i class="bi bi-trash-fill"></i> Delete
                    </button>

                    <a href="{% url 'notes:update-note' note.id %}" class="btn btn-secondary"><i class="bi bi-pencil-fill"></i> Edit</a>
                    
                    <form action="{% url 'notes:pin-note-on-page' note.id %}" method="post" class="d-inline">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-pin">
                            {% if note.is_pinned %}<i class="bi bi-pin-angle-fill"></i> Unpin{% else %}<i class="bi bi-pin"></i> Pin{% endif %}
                        </button>
                    </form>

                    <form action="{% url 'notes:favorite-note-on-page'  note.id%}" method="post" class = 'd-inline'>
                        {% csrf_token %}
                        <button  note-is-fav = {{note.is_favorite}} type = 'submit' class = 'btn fav-btn'>
                            {% if note.is_favorite %}
                                <i style = "font-size: 1.9rem; color:gold;"  class="bi bi-star-fill favorite_icon"></i>
                            {% else %}
                                <i style = "font-size: 1.9rem; color:gold;" class="bi bi-star favorite_icon"></i>
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        {% empty %}
            <p class="empty-message">No notes yet. Start by adding one! 🚀</p>
        {% endfor %}
    </div>
</div>

<!-- Delete Confirmation Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <form id="deleteForm" method="post" data-base-url="{% url 'notes:delete-note' 0 %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

notes/templates/notes/home_page.html
{% extends "layout.html" %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
<section class="hero-section d-flex align-items-center text-center text-light">
  <div class="container">
    <h1 class="display-4 fw-bold">Welcome to <span class="text-warning">NoteMaster</span></h1>
    <p class="lead">Your personal space to organize thoughts, ideas, and projects with ease.</p>
    <a href="{% url 'notes:notes_page' %}" class="btn btn-lg btn-warning rounded-pill shadow-sm mt-3">
      <i class="bi bi-journal-text"></i> Get Started
    </a>
  </div>
</section>

<section class="features-section py-5">
  <div class="container">
    <div class="row text-center mb-4">
      <h2 class="fw-bold">Why Choose NoteMaster?</h2>
      <p class="text-muted">We help you stay productive and organized, anytime, anywhere.</p>
    </div>
    <div class="row g-4">
      <div class="col-md-4">
        <div class="card h-100 shadow-sm border-0 rounded-4">
          <div class="card-body text-center">
            <i class="bi bi-pencil-square fs-1 text-primary"></i>
            <h5 class="mt-3 fw-bold">Easy Note Taking</h5>
            <p class="text-muted">Quickly create, edit, and delete notes with a user-friendly interface.</p>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card h-100 shadow-sm border-0 rounded-4">
          <div class="card-body text-center">
            <i class="bi bi-folder-fill fs-1 text-success"></i>
            <h5 class="mt-3 fw-bold">Organize by Categories</h5>
            <p class="text-muted">Keep your notes structured with custom categories tailored to your needs.</p>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card h-100 shadow-sm border-0 rounded-4">
          <div class="card-body text-center">
            <i class="bi bi-pin-angle-fill fs-1 text-danger"></i>
            <h5 class="mt-3 fw-bold">Pin Important Notes</h5>
            <p class="text-muted">Highlight the most important notes by pinning them for quick access.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="cta-section text-center py-5 bg-light">
  <div class="container">
    <h2 class="fw-bold">Ready to Boost Your Productivity?</h2>
    <p class="text-muted">Join our growing community of users who organize their lives with NoteMaster.</p>
    {% if not user.is_authenticated %}
    <a href="{% url 'users:register-user' %}" class="btn btn-primary btn-lg rounded-pill shadow-sm">
      <i class="bi bi-person-plus-fill"></i> Create an Account
    </a>
    {% endif %}
  </div>
</section>
{% endblock content %}

notes/templates/notes/notes_page.html
{% extends "layout.html" %}

{% block title %}
    Notes Page
{% endblock title %}

{% block content %}
<div class="notes-container">
    <div class = 'dashbord-container'>
        <h1><i class="bi bi-bar-chart-fill"></i>Dashbord</h1>
        <div class="row mb-4">
        <div class=" col-12 col-sm-6 col-md-3">
            <div class="card text-center shadow-sm">
            <div class="card-body dash-card">
                <h5 class="card-title">Total Notes</h5>
                <p class="display-6">{{ total_notes }}</p>
            </div>
            </div>
        </div>
        <div class=" col-12 col-sm-6 col-md-3">
            <div class="card text-center shadow-sm">
            <div class="card-body dash-card">
                <h5 class="card-title">Pinned</h5>
                <p class="display-6">{{ pinned_notes }}</p>
            </div>
            </div>
        </div>
        <div class=" col-12 col-sm-6 col-md-3">
            <div class="card text-center shadow-sm">
            <div class="card-body dash-card">
                <h5 class="card-title">Favorites</h5>
                <p class="display-6">{{ favorite_notes }}</p>
            </div>
            </div>
        </div>
        <div class=" col-12 col-sm-6 col-md-3">
            <div class="card text-center shadow-sm">
            <div class="card-body dash-card">
                <h5 class="card-title">Categories</h5>
                <p class="display-6">{{ total_categories }}</p>
            </div>
            </div>
        </div>
        </div>
    </div>
    <div class="notes-header">
        <h1><i class="bi bi-journal-bookmark-fill"></i> Your Notes</h1>
        <a href="{% url 'notes:add-note' %}" class="btn btn-primary"><i class="bi bi-patch-plus-fill"></i> Add Note</a>
    </div>

    <div class="notes-list">

        <!-- Toasts container -->
        <div class="toast-container position-fixed bottom-0 end-0 p-3" style="z-index: 1100">
            {% if messages %}
                {% for message in messages %}
                <div class="toast align-items-center text-bg-{{ message.tags }} border-0 mb-2"
                    role="alert" aria-live="assertive" aria-atomic="true"
                    data-bs-delay="4000" data-bs-autohide="true">
                    <div class="d-flex">
                        <div class="toast-body">
                            {{ message }}
                        </div>
                        <button type="button" class="btn-close btn-close-white me-2 m-auto"
                                data-bs-dismiss="toast" aria-label="Close"></button>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
        </div>

        {% for note in notes %}
            <div class="note-card">
                <div class="note-header">
                    <h2>{{ note.title }}</h2>
                    <span class="note-date">{{ note.date|date:"M d, Y H:i" }}</span>
                </div>
                <p class="note-content">{{ note.content }}</p>

                <div class="note-actions">

                    <!-- Delete button triggers modal -->
                    <button type="button" class="btn btn-danger" 
                            data-bs-toggle="modal" 
                            data-bs-target="#deleteModal" 
                            data-note-id="{{ note.id }}"
                            data-note-title = "{{note.title}}"
                            >
                        <i class="bi bi-trash-fill"></i> Delete
                    </button>

                    <a href="{% url 'notes:update-note' note.id %}" class="btn btn-secondary"><i class="bi bi-pencil-fill"></i> Edit</a>
                    
                    <form action="{% url 'notes:pin-note' note.id %}" method="post" class="d-inline">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-pin">
                            {% if note.is_pinned %}<i class="bi bi-pin-angle-fill"></i> Unpin{% else %}<i class="bi bi-pin"></i> Pin{% endif %}
                        </button>
                    </form>

                    <form action="{% url 'notes:favorite-note'  note.id%}" method="post" class = 'd-inline'>
                        {% csrf_token %}
                        <button  note-is-fav = {{note.is_favorite}} type = 'submit' class = 'btn fav-btn'>
                            {% if note.is_favorite %}
                                <i style = "font-size: 1.9rem; color:gold;"  class="bi bi-star-fill favorite_icon"></i>
                            {% else %}
                                <i style = "font-size: 1.9rem; color:gold;" class="bi bi-star favorite_icon"></i>
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        {% empty %}
            <p class="empty-message">No notes yet. Start by adding one! 🚀</p>
        {% endfor %}
    </div>
</div>

<!-- Delete Confirmation Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <form id="deleteForm" method="post" data-base-url="{% url 'notes:delete-note' 0 %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

notes/templates/notes/search_page.html
{% extends "layout.html" %}


{% block title %}
    Search Page
{% endblock title %}

{% block content %}
    {% if searched %}
<div class="notes-container">
    <div class="notes-header">
        <h1>📝 You Searched for {{searched}}</h1>
    </div>

    <div class="notes-list">
        {% for note in notes %}
            <div class="note-card">
                <div class="note-header">
                    <h2>{{ note.title }}</h2>
                    <span class="note-date">{{ note.date|date:"M d, Y H:i" }}</span>
                    <span class="note-date">{{note.category}}</span>
                </div>
                <p class="note-content">{{ note.content }}</p>
            </div>
        {% empty %}
            <p class="empty-message">There is no note with this name!</p>
        {% endfor %}
    </div>
</div>
    {% else %}
    <div class = 'home-page-div'>
        <h1>You didn t searched for anything</h1>
    </div>
    {% endif %}
{% endblock content %}

notes/templates/notes/update_note.html
{% extends "layout.html" %}

{% block title %}
    Update Note
{% endblock title %}

{% block content %}
<div class="form-page">
    <div class="form-card">
        <h1><span class="icon"><i class="bi bi-pencil-square"></i></span>Edit your Note</h1>
        <form action="" method="post">
            {% csrf_token %}
            
            <label for="title">Title</label>
            {{ form.title }}

            <label for="content">Content</label>
            {{ form.content }}

            <label for="category">Category</label>
            {{ form.category }}
            <button type="submit">Edit Note</button>
        </form>
    </div>
</div>
{% endblock content %}