notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'


urlpatterns = [
    ################## Notes urls##############################

    path('', views.home_page,name='home-page'),
    path('notes-page/', views.notes_page, name='notes_page'),
    path('add-note/', views.add_note, name='add-note'),
    path('delete-note/<note_id>',views.delete_note,name='delete-note'),
    path('update-note/<note_id>',views.update_note,name='update-note'),
    path('search-page/', views.search_page, name = 'search-page'),
    path('pin-note/<note_id>', views.pin_note,name='pin-note'),
    path('favorite-note/<note_id>', views.favorite_note,name='favorite-note'),
    path('favorite-notes-page', views.favorite_notes_page, name="favorite-notes-page"),

    ############ Cateogries urls#######################

    path('category-page/<category_id>', views.category_page,name='category-page'),

    path('add-note-category/<category_id>', views.add_note_category, name='add-note-category'),

    path('delete-note-category/<note_id>/<category_id>',views.delete_note_category,name='delete-note-category'),

    path('update-note-category/<note_id>/<category_id>',views.update_note_category,name='update-note-category'),

    path('add-category', views.add_category, name='add-category'),

    path('delete-category/<category_id>', views.delete_category,name='delete-category'),

    path('update-category/<category_id>', views.update_category,name='update-category'),

    path('pin-category-note/<note_id>/<category_id>', views.pin_category_note,name='pin-category-note'),

    path('favorite-category-note/<note_id>/<category_id>', views.favorite_category_note,name='favorite-category-note'),

    #### Favorite notes page########
    path('pin-note_on_page/<note_id>', views.pin_note_on_page,name='pin-note-on-page'),
    path('favorite-note-on-page/<note_id>', views.favorite_note_on_page,name='favorite-note-on-page'),

]

notesapp/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('',include('notes.urls')),
    path('users/',include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'


urlpatterns = [
    path('register/', views.register_user, name = 'register-user'),
    path('login/', views.login_user, name = 'login-user'),
    path('logout/', views.logout_user, name = 'logout-user'),
    
]

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar sticky-top navbar-expand-lg " style = "background-color: #898AC4;">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'notes:notes_page' %}">Notes</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <li style="text-align:center;">
              <a class="dropdown-item" href="{% url 'notes:add-category' %}">Add Category</a>
            </li>
            <li style = "text-align:center;"><a class="dropdown-item" href="{% url 'notes:notes_page' %}">General</a></li>
            {% for category in categories %}
            <li class="dropdown-item d-flex justify-content-between align-items-center">
              <a class='dropdown-item dropdown-link' href="{% url 'notes:category-page' category.id%}">{{ category.name }}</a>
              <div class="category-actions">
                <a class="dropdown-item action-icon edit" href="{% url 'notes:update-category' category.id %}" title="Edit">
                  <i class="bi bi-pen"></i>
                </a>
                <form action="{% url 'notes:delete-category' category.id %}" method="post" style="display:inline;">
                  {% csrf_token %}
                  <button type="submit" class="action-icon delete" title="Delete"><i class="bi bi-trash3"></i></button>
                </form>
              </div>
            </li>
          {% endfor %}
        </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'notes:favorite-notes-page' %}">Favorite Notes</a>
        </li>
        {% endif %}
        {% if not  user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:register-user' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login-user' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
    {% if user.is_authenticated %}
      <div class="nav-item mx-auto search-bar">
      <form action="{% url 'notes:search-page' %}" method="post" class="d-flex align-items-center justify-content-center">
        {% csrf_token %}
        <input autocomplete = 'off' type="search" aria-label="search" placeholder="Search notes..." name="searched" class="search-input">
        <button type="submit" class="search-btn">🔍</button>
      </form>
      </div>
    {% endif %}
    {% if user.is_authenticated %}
      <form action="{% url 'users:logout-user' %}" method="post">
          {% csrf_token %}
          <button class="logout-btn">Logout</button>
      </form>
    {% endif %}
  </div>
</nav>

{% block content %}
    
{% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
</body>

<script src="{% static 'js/main.js' %}"></script>
</html>